# Generated by Django 4.2.7 on 2023-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, unique=True)),
                ('branch_caption', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('view', models.JSONField(null=True)),
            ],
        ),
    ]
